# -*- coding: utf-8 -*-
"""Jaswanth_Assignment_5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WI964iaxKQTmQBJMwOa1KM7h182-qrbC
"""

import pandas as pd
import numpy as np

"""### Understanding The Data"""

df = pd.read_csv('/content/Mall_Customers.csv')

df.head()

df.shape

df.info()

df.describe()

df.isnull().sum()

df.Gender.value_counts()

"""### Data Preprocessing"""

new_df = df
new_df = new_df.drop(['CustomerID'],axis=1)

new_df.head()

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

new_df['Gender'] = le.fit_transform(new_df['Gender'])

new_df.head()

"""### K-Means Algorithm"""

from sklearn import cluster

error = []
for i in range(1,11):
  kmeans = cluster.KMeans(n_clusters=i,init='k-means++',random_state=0)
  kmeans.fit(new_df)
  error.append(kmeans.inertia_)

error

import matplotlib.pyplot as plt
plt.plot(range(1,11),error)

km_model = cluster.KMeans(n_clusters=5,init="k-means++",random_state=0)
km_model.fit(new_df)

km_model.predict(new_df)

"""### Predicting Random Values"""

km_model.predict([[1,20,50,35]])

km_model.predict([[0,22,50,35]])

km_model.predict([[0,50,100,50]])

km_model.predict([[0,43,60,20]])